Redesigned background task to be long-running and added logger
TahaNKhan/Deployr pull request #11
Opened 2020-07-08 06:01 UTC by amir734jj

2020-07-13 16:56 UTC, TahaNKhan requested changes

2020-07-13 16:56 UTC, TahaNKhan commented on Deployr.Processor/BackgroundDeployrTask.cs
> +        public CancellationTokenSource CancellationToken { get; }
CancellationTokenSource

2020-07-13 16:56 UTC, TahaNKhan commented on Deployr.Processor/BackgroundDeployrTask.cs
> +            }, null, token, TaskCreationOptions.LongRunning, TaskScheduler.Default);
Good call

2020-07-13 16:56 UTC, TahaNKhan commented on Deployr.Processor/BackgroundDeployrTask.cs
> +                while (!CancellationToken.IsCancellationRequested)
All of this should be surrounded by a try catch block, so we don’t exit the application on an exception

2020-07-14 03:26 UTC, amir734jj commented
Updated the code.

2020-07-27 12:13 UTC, TahaNKhan approved these changes

2020-07-27 14:18 UTC, merged